[build]

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"

# gnueabihf target seems not working
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

# brew install arm-linux-gnueabihf-binutils
# rustup target add armv7-unknown-linux-gnueabihf
# rustup target add armv7-unknown-linux-musleabihf